appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: P0cWfq3PeMwsJnnEAvkiXgHNwK/o7lI4nQ1RyD+8oEzcHaNb29cD/oLmKw9XYJu5DvW1ekiMnKIb83guuCx4xRe+EN//6xQsUx5UAuQzaptyoIlbCgj2gIsuFfiaYKuYGWpSp+XIVqaCLFBIr4VazXxxfI+HSsKHnBViJqychvB3bGmkUzPnlokWzRcGuja95ncyJSIeLHoTcJNH6xlW7chs+jnWACvE6YBcS1lyQcJtvqZT2mygG7zCV3pGQxvELE5jR0Q69jb4/rpuQxcEEsjD10OkuvBerVRNiGNz96nxZt+FJWytBdWucZCm2JU3wIUnjb1ysPlg4cUOs4Qad+TMKR+8ujiEHmTtD0gzxf9xoBYs2PiFuZNtcsLnDoWlgFeA1UrgE9IRmLzAIRhS3o0UzKkU6dW5DJ6nBIaa3b3c8L03mi0FK4KVtRwYm5DQXYZJY7WXU5lPlAxHFZiD0KILg1PaOQAbKpVoXGsDu9KN1QFwmi0L/+fYbfeiy4XToi726czbCTNgkd8QQrzyz6zK5Hf48IpXDtxv9A4vV3Fju/8ZYjYogMTA+Jn0PvYD+AoRpR55PRaLTK4R6988KiVRfoJbQxKOvGb7szH22fdz/RxQsFw1mVIVyT3Qr0xnGFZOnJrR3D00cMdPo+IVsoOTwe/c56/H9pj1r45P8Yg=}
